// Generates the icon CSS + the IconName type union from the Cursor icon font's
// name->codepoint map, and copies the woff2 into public/fonts so the repo is
// self-contained. Re-run with `npm run gen:icons` if the font is updated.
//
// Source can be overridden via CURSOR_ICONS_DIR.
import { mkdirSync, readFileSync, writeFileSync, copyFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

const SRC_DIR =
  process.env.CURSOR_ICONS_DIR ||
  "/Users/rikkimukherjee/Documents/Plugins/cursor-icons/source/icons/export/16";

const FONT_FILE = "Cursor Icons 16.woff2";
const MAP_FILE = "Cursor Icons 16.json";
const FONT_FAMILY = "Cursor Icons";
const PUBLIC_FONT_PATH = "/fonts/Cursor Icons 16.woff2";

const map = JSON.parse(readFileSync(join(SRC_DIR, MAP_FILE), "utf8"));
const names = Object.keys(map).sort();

// 1) Copy the font into public/fonts
mkdirSync(join(ROOT, "public/fonts"), { recursive: true });
copyFileSync(join(SRC_DIR, FONT_FILE), join(ROOT, "public/fonts", FONT_FILE));

// 2) icons.css
const header = `/* AUTO-GENERATED by scripts/gen-icons.mjs. Do not edit by hand. */
@font-face {
  font-family: "${FONT_FAMILY}";
  src: url("${PUBLIC_FONT_PATH}") format("woff2");
  font-weight: normal;
  font-style: normal;
  font-display: block;
}

[class^="icon-"]::before,
[class*=" icon-"]::before {
  font-family: "${FONT_FAMILY}" !important;
  font-style: normal;
  font-weight: normal !important;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
`;

// Emit the literal glyph character (PUA codepoint) rather than a "\\f40a" CSS
// escape: PostCSS/Vite strip unicode escapes in content strings, but a raw
// UTF-8 character passes through untouched.
const rules = names
  .map((name) => {
    const ch = String.fromCodePoint(Number(map[name]));
    return `.icon-${name}::before { content: "${ch}"; }`;
  })
  .join("\n");

mkdirSync(join(ROOT, "src/styles"), { recursive: true });
writeFileSync(join(ROOT, "src/styles/icons.css"), `${header}\n${rules}\n`, "utf8");

// 3) iconNames.ts (type-only union; no runtime cost)
const union = names.map((n) => `  | ${JSON.stringify(n)}`).join("\n");
const tsHeader = `// AUTO-GENERATED by scripts/gen-icons.mjs. Do not edit by hand.\n`;
mkdirSync(join(ROOT, "src/icons"), { recursive: true });
writeFileSync(
  join(ROOT, "src/icons/iconNames.ts"),
  `${tsHeader}export type IconName =\n${union};\n`,
  "utf8",
);

console.log(
  `Generated ${names.length} icons -> src/styles/icons.css, src/icons/iconNames.ts, public/fonts/${FONT_FILE}`,
);
